### PR TITLE
Wps fix 2

### PR DESCRIPTION
**Pull request by m5kro**
Fixes issue where [line endings](https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html#:~:text=Text%20files%20created%20on%20DOS,(%22%5Cn%22).) were in DOS format. Line endings are now in UNIX format.

Fixes issues with interfering with management AP interface. Now uses the same interface for iwlist and airodump-ng.

Interface selection now starts at wlan1 (or highest wlan) instead of wlan0.

### CODE REVIEW

**Comment by xchwarze** [comment]
Wouldn't it be the right thing to use some of the functions that are available in the default installed modules?
I mean all the helpers that can be found in paths like these

https://github.com/xchwarze/wifi-pineapple-panel/tree/wpc/src/pineapple/modules/PineAP/api
https://github.com/xchwarze/wifi-pineapple-panel/tree/wpc/src/pineapple/modules/Networking/api

It always seemed wrong to me that the modules developed for this platform do not rely on the helpers already created. I understand that it was partly hak5's fault for not being clear and not documenting better.

**Comment by m5kro** [comment]
Yeah, I get what you mean. I originally wanted to use the recon function instead of the overcomplicated iw scan code and use the pineAP functions for monitor mode. However, the issue with both functions is that they only use the wlan1 interface. On the original Nano and Tetra this didn't matter as they had powerful radios but with this project the routers could be underpowered, meaning a USB adapter would be needed. Thus I kept the original code so users could which adapter to use.

**Comment by xchwarze** [comment]
The recognition interface is configurable. It is in the PineAP section.

Then about the line endings, were there any broken scripts for that?
Because in the diff I don't see any change about it, even this repo has several modules with wrong line endings. But as they are not scripts they work anyway.

**Comment by m5kro** [comment]
Sorry for taking so long, I see what you mean about PineAP. But I still think the current system is better as it does not interfere with running PineAP operations. I'll probably use [interfaceActions()](https://github.com/xchwarze/wifi-pineapple-panel/blob/wpc/src/pineapple/modules/Networking/api/module.php) from the networking API instead. I'm also trying to use the recon API in place of the old iwscan stuff.

As for the line endings, they only matter in the shell scripts as bash thinks there is something there with DOS endings. I used:
`sed 's/\r$//' oldwps.sh > wps.sh`
to convert the shell scripts to UNIX format.

**Pull request merged**
